name: ex00_checkout_basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  mind_paystack: ^0.1.0+1
  mocktail: ^1.0.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
