name: sample_payment_dart
description: A sample command-line application.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  mind_paystack: ^0.1.0+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
