name: mind_paystack
description: My new Dart package
version: 0.1.1+1
homepage: https://github.com/Dartmind-OpenSource/mind-paystack

environment:
  sdk: ^3.5.0

dependencies:
  dart_mappable: ^4.6.0
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  logger: ^2.5.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  mockito: ^5.4.4
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  dart_mappable_builder: ^4.5.0
