import 'package:dart_mappable/dart_mappable.dart';

part 'customer.mapper.dart';

/// Represents customer information associated with a transaction.
/// 
/// This model contains customer details including contact information,
/// unique identifiers, and risk assessment data from Paystack.
/// 
/// Example usage:
/// ```dart
/// final customer = Customer(
///   id: 123456,
///   email: 'customer@example.com',
///   customerCode: 'CUS_abc123',
///   firstName: 'John',
///   lastName: 'Doe',
/// );
/// ```
@MappableClass()
class Customer with CustomerMappable {
  /// Creates a new Customer instance.
  /// 
  /// The [id], [email], and [customerCode] are required fields.
  const Customer({
    required this.id,
    required this.email, required this.customerCode, this.firstName,
    this.lastName,
    this.phone,
    this.metadata,
    this.riskAction,
  });
  /// Unique identifier for the customer in Paystack's system.
  final int id;
  
  /// Customer's first name.
  final String? firstName;
  
  /// Customer's last name.
  final String? lastName;
  
  /// Customer's email address.
  /// 
  /// This is used for transaction notifications and customer identification.
  final String email;
  
  /// Unique customer code generated by Paystack.
  /// 
  /// This code can be used to identify the customer across multiple
  /// transactions and API calls.
  @MappableField(key: 'customer_code')
  final String customerCode;
  
  /// Customer's phone number.
  final String? phone;
  
  /// Custom metadata attached to the customer.
  /// 
  /// Can contain any additional information stored with the customer,
  /// such as preferences, internal IDs, or business-specific data.
  final dynamic metadata;
  
  /// Risk assessment action taken for this customer.
  /// 
  /// Indicates any risk-related actions or flags applied to the customer
  /// based on Paystack's fraud detection systems.
  @MappableField(key: 'risk_action')
  final String? riskAction;
}
