name: mind_paystack_flutter
description: My new Flutter package
version: 0.1.1
homepage: https://github.com/Dartmind-OpenSource/mind-paystack
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  mind_paystack: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
