name: ex01_checkout_flutter
description: "A new Flutter project."
homepage: https://github.com/Dartmind-OpenSource/mind-paystack
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  mind_paystack: ^0.1.2+1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env