name: ex02_charge_terminal
description: Terminal application demonstrating MindPaystack charge flows with card processing.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  mind_paystack:
    path: ../../packages/mind_paystack
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
